### ISSUE TITLE
Tracking: CHAOSS Community Handbook -> Knowledgebase

### ISSUE THREAD

**Issue by jwflory** [chaoss/community#321]
# Summary

Track topics and content in the process of being created or maintained for future inclusion in the future CHAOSS website knowledgebase.

# Background

In the D.E.I. Working Group and others, there is documentation and information about community workings that need to go somewhere. The CHAOSS Handbook is the current place we put this information, but the access is uncertain and there is a proposed mentored project happening this round for adding a knowledgebase to the CHAOSS website. The purpose of this issue is to track different pieces of documentation that are either newly created or updates to existing content, so they can then be implemented on the future CHAOSS website knowledgebase.

# Details

## Docs To be Added

- [ ] **Mentored Projects documentation** (@kristiprogri): Unifying documentation, best practices, and steps for organizers of mentored project programs, e.g. Outreachy, GSoC, GSoD, etc.
- [ ] **Newcomer Slack Bot documentation** (@ElizabethN): Include docs from the [chaoss-slack-bot](https://github.com/chaoss/chaoss-slack-bot) repo
- [ ] **Metrics that are not going back under review** documentation
 - One issue to translations once changes have been made 
 - Update the spreadsheet 
 - [ ] **Metrics that are going back under review** documentation
 - Single issue per metric for new translation

## Docs To be Edited/Updated
- [ ] **CHAOSScast documentation** (@ElizabethN): This set of docs is really out of date and needs to be updated.
- [ ] **Website information** (@klumb): This set of docs needs to be updated.
- [ ] **Metrics Release Process**
- [ ] **Terminology**: This doc is missing key terms like "metrics" and "metrics models" and "focus areas" should be updated
- [ ] **Internal Docs** We need to make sure any administrative docs kept in the CHAOSS project Google Drive are referenced in the appropriate places of the Handbook
- [ ]  **Metric definition has changed in a substantial way**

# Outcome

Important efforts on documenting the CHAOSS Community are not lost during this time of transition

**Comment by ElizabethN** [comment]
cc @klumb: we decided in the DEI Working Group to start this issue so that additions to the handbook/knowledgebase don't get lost. We can let other working groups know that if they're adding or creating docs to just put a placeholder here for future inclusion, as @jwflory mentioned above.

**Comment by ElizabethN** [comment]
Placeholder for me to include docs on the [Newcomer Slack Bot](https://github.com/chaoss/chaoss-slack-bot).

**Comment by ElizabethN** [comment]
@Ruth-ikegah @xiaoya-yaya as you both finish up the Handbook GSoD project, can you confirm for me that these points are covered somewhere in the new docs? Then I'll be able to close this issue. Thank youuuuu 🙏 😍

**Comment by xiaoya-yaya** [comment]
### Docs to be added
- [ ] The mentorship projects documentation is unified under the [how-to-contribute/mentorship](https://github.com/chaoss/community/tree/main/how-to-contribute/mentorship) folder
- [ ] The [Slack Bot documentation](https://github.com/chaoss/community/blob/main/how-work-is-done/community-projects/chaoss-slack-bot.md)
- [ ] The metrics review related documentation is described in the [metric contribution guide](https://github.com/chaoss/community/blob/main/how-to-contribute/contributing-to-chaoss/metrics-contribution.md) and [metrics release page](https://github.com/chaoss/community/blob/main/how-work-is-done/chaoss-working-groups/metrics-releases.md)

### Docs To be Updated
Yes, I believe these have been updated, perhaps need to be confirmed and reviewed by the community.

**Comment by ElizabethN** [comment]
Can we close this issue @Ruth-ikegah and @xiaoya-yaya ?

**Comment by Ruth-ikegah** [comment]
yes!

**Comment by xiaoya-yaya** [comment]
+1
