### ISSUE TITLE
Tracking: Discourse Implementation

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#461]
This is an issue to help us keep track of all the steps needed to get Discourse up and running. 🏃 

For reference, there is a dump of ideas from the group [here](https://docs.google.com/document/d/1i1k6CN5734Apqdb3HgU6fOoft9JRF00pZudT9uA_VpE/edit). 
Discussion around this also happens in the CHAOSS [#forum-migration-planning](https://chaoss-workspace.slack.com/archives/C034RCGJ3GX) slack channel in the CHAOSS slack.

## Setup
- [x] Get approval from Discourse to host under an open source account or switch to Standard Plan with payment
- [x] Set up initial categories
- [x] Grant access to the initial admin team
- [x] [Create a list of initial tags](https://github.com/chaoss/community/issues/466)
- [x] Decide who will be on the moderation team
- [x] [Write a moderation guide](https://github.com/chaoss/community/issues/467)
- [x] Write a "Getting Started" guide
- [x] Write a Privacy Policy doc
- [x] Write a Terms of Service doc
- [x] Write a FAQ/Guide doc (link to Code of Conduct?)
- [x] Determine initial set of badges (the default ones are kind of meh)

~~-  Decide how this will integrate with the Website and Slack, if at all~~
~~- Install plugins to website, if needed~~
~~- Install integrations to slack, if needed~~

## Outreach
~~- Notify mailing list subscribers that we will eventually be sunsetting the mailing lists~~
- [x] Announce on Slack
- [x] Announce in Newsletter
- [x] Announce at community meetings and working group meetings 
- [x] Add Discourse link to newsletter 
- [x] Add Discourse link to Website
- [x] Add Discourse info to community handbook

**Comment by ElizabethN** [comment]
We plan to launch Discourse on Feb 1, 2023 - yay! Regarding these bits, we should wait a few months on this, until we can get it up and running smoothly: 

> - Decide how this will integrate with the Website and Slack, if at all
>-  Install plugins to website, if needed
> - Install integrations to slack, if needed

Otherwise it's a matter of announcing and promoting.
